language: "perl"
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

# branches:
#   only:
#     - master
notifications:
  recipients:
    - perl@rainboxx.de
  email:
    on_success: change
    on_failure: always
#env: